config/routes.rb
Colchonet::Application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope '(:locale)', locale: LOCALES do
    resources :rooms
    resources :users

    resource :confirmation, only: [:show]
    resource :user_sessions, only: [:create, :new, :destroy]
  end

  resources :rooms do
    resources :reviews, only: [:create, :update], module: :rooms
  end

  get '/:locale' => 'home#index', locale: LOCALES
  root 'home#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  # Criamos um Array de 5 elementos, ao invés de range.
  POINTS = (1..5).to_a
  belongs_to :user
  belongs_to :room, counter_cache: true
  validates_uniqueness_of :user_id, scope: :room_id
  validates_presence_of :points, :user_id, :room_id
  validates_inclusion_of :points, in: POINTS

  def self.stars
    (average(:points) || 0).round
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend FriendlyId

  has_many :reviews, dependent: :destroy
  belongs_to :user
  scope :most_recent, -> { order('created_at DESC') }

  validates_presence_of :title
  validates_presence_of :slug

  mount_uploader :picture, PictureUploader
  friendly_id :title, use: [:slugged, :history]




  def self.search(query)
    where(['location LIKE :query OR
title LIKE :query OR
description LIKE :query', query: "%#{query}%"])
  end

  def complete_name
    "#{title}, #{location}"
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  # Aproveite a oportunidade para atualizar o outro
  # relacionamento:
  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Lembre-se de tirar as validações de senha!
  # O has_secure_password já o faz para você.
  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, minimum: 30, allow_blank: false
  validates_format_of :email, with: EMAIL_REGEXP
  has_secure_password

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :most_recent, -> { order('created_at DESC') }

  def self.authenticate(email, password)
    user = confirmed.find_by(email: email)
    user.authenticate(password) if user.present?
  end

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?
    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model
  attr_accessor :email, :password
  validates_presence_of :email, :password
  def initialize(session, attributes = {})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate!
    user = User.authenticate(@email, @password)
    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?
  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
                  alert: t('flash.alert.needs_login')
    end
  end

  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end

  def user_session
    UserSession.new(session)
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])
    if user.present?
      user.confirm!
      redirect_to user,
                  notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(3)
  end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_filter :require_authentication
  def create
    review = room.reviews
             .find_or_initialize_by(user_id: current_user.id)
    review.update!(review_params)
    head :ok
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params
      .require(:review).permit(:points)
  end
end

app/controllers/rooms/reviews_controllers.rb
class Rooms::BaseController < ApplicationController
  before_filter :require_authentication

  private

  def room
    @room ||= Room.find(params[:id])
  end
end

class Rooms::ReviewsController < Rooms::BaseController
  def create
    review = room.reviews.
      find_or_initialize_by(user_id: current_user.id)
    review.update!(review_params)
    head :ok
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params
      .require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 3
  before_action :require_authentication,
                only: [:new, :edit, :create, :update, :destroy]
  def index
    @search_query = params[:q]
    rooms = Room.search(@search_query)
            .page(params[:page])
            .per(PER_PAGE)
    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
   end

  def show
    room_model = Room.find(params[:id])
    @room = RoomPresenter.new(room_model, self)

  end

  def new
    @room = current_user.rooms.build
  end

  def edit
    @room = current_user.rooms.find(params[:id])
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: 'new'
    end
  end

  def update
    @room = current_user.rooms.find(params[:id])
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: 'edit'
    end
  end

  def destroy
    @room = current_user.rooms.find(params[:id])
    @room.destroy
    redirect_to rooms_url
  end

  private

  def room_params
    params
      .require(:room)
      .permit(:title, :location, :description, :picture)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy

  def new
    @user_session = UserSession.new(session)
  end

  def create
    @user_session = UserSession.new(session, params[:user_session])
    if @user_session.authenticate!
      # Não esqueça de adicionar a chave no i18n!
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save

      Signup.confirm_email(@user).deliver
      redirect_to @user,
                  notice: 'Cadastro criado com sucesso!'
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user,
                  notice: 'Cadastro atualizado com sucesso!'
    else
      render action: :edit
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:email, :full_name, :location, :password,
              :password_confirmation, :bio)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
        class: 'error_message'
      )
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>
<ul>
  <% @rooms.each do |room| %>

  <li><%= link_to room.complete_name, room %>
  </li>
  <% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %>
    </li>
    <li><%= link_to t('layout.rooms'), rooms_path %>
    </li>
    <li>
      <%= link_to t('layout.my_profile'),
user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path,
method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %>
    </li>
    <li><%= link_to t('layout.signup'), new_user_path %>
    </li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Colchonet</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag  "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
</head>

<body>

  <header>
    <div id="header-wrap">
      <h1>
        <%= link_to "colcho.net", root_path %>
      </h1>
      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
          <% else %>
            <%= render 'layouts/visitor_navbar' %>
              <% end %>
    </div>
  </header>
  <div id="content">
    <% if notice.present? %>
      <p id="notice">
        <%= notice %>
      </p>
      <% end %>
        <% if alert.present? %>
          <p id="alert">
            <%= alert %>
          </p>
          <% end %>
            <%= yield %>
  </div>

</body>

</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
<% if @room.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@room.errors.count, "error") %>
    prohibited this room from being saved:</h2>

  <ul>
    <% @room.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :location %><br>
  <%= f.text_field :location %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>

<p>
<%= f.label :picture %>
<%= f.file_field :picture %>
<%= error_tag @room, :picture %>
</p>


<div class="actions"><%= f.submit %>
</div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
  <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
  <% room.stars.times do %>
  <span class="star filled_star"></span>
  <% end %>
  <% (room.review_points.max - room.stars).times do %>
  <span class="star empty_star"></span>
  <% end %>
  <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point  %>
      <%= f.label :points, value: point do %>
        <%= fa_icon 'star' %>
      <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
    <%= t('.login_to_review') %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2><%= link_to highlight(room.title, @search_query), room.route %></h2>

  <%= render :partial => 'review', :locals => {:room => room} %>

  <span class="created">
    <%= t '.owner_html',
      :owner => room.user.full_name,
      :when => l(room.created_at, :format => :short) %>
  </span>

  <p>
    <span class="location">
      <%= link_to highlight(room.location, @search_query),
                  "https://maps.google.com/?q=#{room.location}",
                  :target => :blank %>
    </span>
  </p>

  <%= link_to(image_tag(room.thumb_url), room.picture_url) if room.has_picture? %>

  <p><%= highlight(room.description, @search_query) %></p>

  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
      <li><%= link_to t('.destroy'), room_path(room.route),
        :method => :delete, :data => {:confirm => t('dialogs.destroy')} %>
      </li>
    </ul>
  <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
<%= text_field_tag :q, @search_query,
placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %> </h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>
<h1>
  <% if @search_query.present? %>
  <%= t '.search_results' %>
  <% else %>
  <%= t '.title' %>
  <% end %>
</h1>
<%= render @rooms %>
<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %>
</h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html',
link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
  <%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>
<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>
<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %>
</h1>
<% if @user_session.errors.has_key? :base %>
<div id="error_explanation">
  <%= @user_session.errors[:base].join(', ') %>
</div>
<% end %>
<%= form_for @user_session do |f| %>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= error_tag @user_session, :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= error_tag @user_session, :password %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<p><%= link_to t('.sign_up'), new_user_path %>
</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<%= t 'general.form_error' %>
</div>
<% end %>

<%= form_for @user do |f| %>
<p>
<%= f.label :full_name %>
<%= f.text_field :full_name %>
<%= error_tag @user, :full_name %>
</p>
<p>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= error_tag @user, :location %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= error_tag @user, :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= error_tag @user, :password %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= error_tag @user, :password_confirmation %>
</p>
<p>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <%= error_tag @user, :bio %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %>
</h1>
<%= render 'form' %>
<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %>
</h1>
<%= render 'form' %>
<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
</p>
<h1>Perfil:
  <%= @user.full_name %>
</h1>
<ul>
  <li>Localização:
    <%= @user.location %>
  </li>
  <li>Bio:
    <%= @user.bio %>
  </li>
</ul>
<%= link_to 'Editar Perfil', edit_user_path(@user) %>